"""empty message

Revision ID: 11e914952b30
Revises: ebcadc872c73
Create Date: 2023-11-20 15:42:02.208496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e914952b30'
down_revision = 'ebcadc872c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_model', schema=None) as batch_op:
        batch_op.drop_column('new_field')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('document_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
