"""empty message

Revision ID: 145962f9336c
Revises: c80c865843f4
Create Date: 2023-11-21 11:01:09.404688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145962f9336c'
down_revision = 'c80c865843f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
