"""empty message

Revision ID: 275503d52722
Revises: df8b70b7b3a3
Create Date: 2023-12-12 10:18:28.471081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275503d52722'
down_revision = 'df8b70b7b3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_item_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('store_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
