"""empty message

Revision ID: 548a2f22c03a
Revises: f532cd1fc5ad
Create Date: 2023-11-25 09:39:53.393540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548a2f22c03a'
down_revision = 'f532cd1fc5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
