"""empty message

Revision ID: df8b70b7b3a3
Revises: 
Create Date: 2023-12-12 09:39:38.485812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8b70b7b3a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_store_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
